python3 -m scripts.predict_patient machines/jupiter1.json generated2/cjweight/axial/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/cjweight/sagittal/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/cjweight/coronal/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/trade011/axial/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/trade011/sagittal/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/trade011/coronal/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/nsathian/axial/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/nsathian/sagittal/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/nsathian/coronal/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/ravis071/axial/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/ravis071/sagittal/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/ravis071/coronal/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/srkrishn/axial/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/srkrishn/sagittal/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/srkrishn/coronal/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/blake367/axial/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/blake367/sagittal/test.json
python3 -m scripts.predict_patient machines/jupiter1.json generated2/blake367/coronal/test.json
